version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "host.docker.internal"
      MYSQL_DATABASE: "smarthome"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
